version: 2
jobs:
  build:
    branches:
      only:
        - master
        - gh-pages
    docker:
      - image: alpine
    steps:
      - add_ssh_keys:
          fingerprints:
            - "90:08:7b:d5:d6:75:ad:d5:97:9f:e0:29:73:f5:ad:1c"
      - checkout
      - run:
          name: helm_tests
          command: sh .circleci/helm_tests.sh